src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# prefix


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sejm_app.urls")),
    path("", include("eli_app.urls")),
    path("", include("articles_app.urls")),
    path("select2/", include("django_select2.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sejm_app/urls.py
from django.urls import path

from .views import (
    EnvoyListView,
    EnvoyDetailView,
    ClubListView,
    ClubDetailView,
    HomeView,
    VotingListView,
    VotingDetailView,
    FAQListView,
    ScandalListView,
    ProcessListView,
    ProcessDetailView,
    SearchResultView,
    UpdateView,
    LastUpdateView,
    CommitteeListView,
    CommitteeDetailView,
    InterpellationDetailView,
    InterpellationListView,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("last-update/", LastUpdateView.as_view(), name="last_update"),
    path("search/", SearchResultView.as_view(), name="search"),
    path("envoys/", EnvoyListView.as_view(), name="envoys"),
    path("envoys/<int:pk>", EnvoyDetailView.as_view(), name="envoy_detail"),
    path("clubs/", ClubListView.as_view(), name="clubs"),
    path("clubs/<str:pk>/", ClubDetailView.as_view(), name="club_detail"),
    path("votings/", VotingListView.as_view(), name="votings"),
    path("voting/<int:pk>/", VotingDetailView.as_view(), name="voting_detail"),
    path("faq/", FAQListView.as_view(), name="faq"),
    path("committees/", CommitteeListView.as_view(), name="committees"),
    path("committee/<str:pk>/", CommitteeDetailView.as_view(), name="committee_detail"),
    path("scandals/", ScandalListView.as_view(), name="scandals"),
    path("processes/", ProcessListView.as_view(), name="processes"),
    path("update/", UpdateView.as_view(), name="update"),
    path("process/<int:pk>/", ProcessDetailView.as_view(), name="process_detail"),
    path("interpellations/", InterpellationListView.as_view(), name="interpellations"),
    path(
        "interpellations/<int:pk>/",
        InterpellationDetailView.as_view(),
        name="interpellation_detail",
    ),
]

src/sejm_app/models/aggregated_model.py
from django.db import models


class AggregatedModel(models.Model):
    max_total_activity = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.pk = 1
        super(AggregatedModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

src/sejm_app/models/club.py
from django.db import models
from django.conf import settings


class Club(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    fax = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    membersCount = models.IntegerField()
    photo = models.ImageField(upload_to="club_logos", null=True, blank=True)

    def __str__(self):
        return f"{self.id}"

    @property
    def api_url(self):
        return settings.CLUBS_URL

src/sejm_app/models/committee.py
from django.conf import settings
from django.db import models
from .envoy import Envoy
from .print_model import PrintModel
from django.utils.functional import cached_property


class CommitteeType(models.TextChoices):
    EXTRAORDINARY = "EXTRAORDINARY", "Nadzwyczajna"
    INVESTIGATIVE = "INVESTIGATIVE", "Śledcza"
    STANDING = "STANDING", "Stała"


class Committee(models.Model):
    name = models.CharField(max_length=512)
    nameGenitive = models.CharField(max_length=512)
    code = models.CharField(max_length=10, primary_key=True, verbose_name="code")
    appointmentDate = models.DateField()
    compositionDate = models.DateField()
    phone = models.CharField(max_length=100, blank=True)
    scope = models.TextField(null=True)
    type = models.CharField(
        max_length=50, choices=CommitteeType.choices, default=CommitteeType.STANDING
    )

    @cached_property
    def first_phone(self):
        return self.phone.split(",")[0]

    def __str__(self):

        return self.name


class MemberFunction(models.TextChoices):
    CHAIR = "CHAIR", "Przewodniczący"
    VICE_CHAIR = "VICE_CHAIR", "zastępca przewodniczącego"


class CommitteeMember(models.Model):
    committee = models.ForeignKey(
        Committee, related_name="members", on_delete=models.CASCADE
    )
    envoy = models.ForeignKey(Envoy, on_delete=models.CASCADE)
    function = models.CharField(
        max_length=100, blank=True, null=True, choices=MemberFunction.choices
    )  # Function within the committee

    class Meta:
        unique_together = ("committee", "envoy")
        ordering = ["function"]

    def __str__(self):
        return f"{self.envoy.full_name()} - {self.committee.name}"


class CommitteeSitting(models.Model):
    agenda = models.TextField()
    closed = models.BooleanField()
    date = models.DateField()
    num = models.IntegerField()
    remote = models.BooleanField()
    video_id = models.CharField(max_length=60, blank=True, null=True)
    committee = models.ForeignKey(
        Committee, on_delete=models.CASCADE, related_name="sittings"
    )
    prints = models.ManyToManyField(PrintModel, related_name="committee_sittings")

    @property
    def video_url(self):
        url = (
            f"{settings.SEJM_ROOT_URL}/videos/{self.video_id}"
            if self.video_id
            else None
        )
        return url

    def __str__(self):
        return f"Committee Sitting {self.num} on {self.date}"

src/sejm_app/models/envoy.py
from django.db import models
from .club import Club

# cached property
from django.utils.functional import cached_property


class Envoy(models.Model):
    id = models.AutoField(primary_key=True)
    photo = models.ImageField(upload_to="photos", null=True, blank=True)
    firstName = models.CharField(max_length=255)
    secondName = models.CharField(max_length=255, null=True, blank=True)
    lastName = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    active = models.BooleanField(default=True)
    inactiveCause = models.CharField(max_length=255, null=True, blank=True)
    waiverDesc = models.TextField(null=True, blank=True)
    districtNum = models.IntegerField()
    districtName = models.CharField(max_length=255)
    voivodeship = models.CharField(max_length=255)
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name="envoys")
    birthDate = models.DateField()
    birthLocation = models.CharField(max_length=255)
    profession = models.CharField(max_length=255)
    educationLevel = models.CharField(max_length=255)
    numberOfVotes = models.IntegerField()
    biography = models.TextField(
        null=True, blank=True, help_text="Biography of the envoy pulled from wikipedia"
    )
    biography_source = models.URLField(
        null=True, blank=True, help_text="URL to the wikipedia page of the envoy"
    )

    @cached_property
    def total_activity(self) -> int:
        return (
            self.votes.count() * 0.2
            + self.interpellations.count()
            + self.processes.count()
        )

    @cached_property
    def is_female(self) -> bool:
        return self.firstName.endswith("a")

    @cached_property
    def title(self) -> str:
        prefix = "Posłanka" if self.is_female else "Poseł"
        return f"{prefix} {self.firstName} {self.lastName}"

    @cached_property
    def full_name(self) -> str:
        return f"{self.firstName} {self.secondName if self.secondName else ''} {self.lastName}"

    def __str__(self):
        return f"{self.firstName} {self.lastName} ({self.club.id})"

src/sejm_app/forms.py
from django import forms
from django_select2.forms import Select2Widget, Select2MultipleWidget
from .models import Club, Process, Envoy, CommitteeType


class EnvoySearchForm(forms.Form):
    searchEnvoys = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control mb-3", "placeholder": "wyszukaj posła..."}
        ),
    )
    club = forms.ModelMultipleChoiceField(
        queryset=Club.objects.all(),
        widget=Select2MultipleWidget(attrs={"class": "form-check-input"}),
        required=False,
    )
    district = forms.ModelChoiceField(
        queryset=Envoy.objects.all().values_list("districtName", flat=True).distinct(),
        empty_label="Wszystkie",
        widget=Select2Widget(attrs={"class": "form-select my-3"}),
        required=False,
    )


# class InterpellationSearchForm(forms.Form):
#     term = forms.IntegerField(
#         required=False,
#         widget=forms.NumberInput(
#             attrs={"class": "form-control mb-3", "placeholder": "Term"}
#         ),
#     )
#     num = forms.IntegerField(
#         required=False,
#         widget=forms.NumberInput(
#             attrs={"class": "form-control mb-3", "placeholder": "Number"}
#         ),
#     )
#     title = forms.CharField(
#         required=False,
#         widget=forms.TextInput(
#             attrs={"class": "form-control mb-3", "placeholder": "Title"}
#         ),
#     )


class CommitteeSearchForm(forms.Form):
    type = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
        label="Typ",
    )
    appointmentDate_from = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
        label="Data mianowania (od)",
    )
    appointmentDate_to = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
        label="Data mianowania (do)",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = CommitteeType.choices


class ProcessSearchForm(forms.Form):
    state = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
        label="Tylko niezakończone",
    )
    documentType = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"class": "form-check-input"}),
        required=False,
        label="Typ dokumentu",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["documentType"].choices = (
            Process.objects.all().values_list("documentType", "documentType").distinct()
        )

src/sejm_app/views/club_detail_view.py
from sejm_app.models import Club, Envoy


from django.views.generic import DetailView


class ClubDetailView(DetailView):
    model = Club
    template_name = "club_detail.html"  # replace with your template
    context_object_name = "club"
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["envoys"] = Envoy.objects.filter(club=context["club"])
    #     return context

src/sejm_app/views/club_list_view.py
from django.db.models import Count
from django.views.generic import ListView
from sejm_app.models import Club

import json


class ClubListView(ListView):
    model = Club
    template_name = "club_list.html"  # replace with your template
    context_object_name = "clubs"

    def get_queryset(self):
        # Annotate each club with the count of its envoys and order by this count
        return Club.objects.order_by("-membersCount")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clubs_list = [
            {"id": club.id, "envoys_count": club.membersCount}
            for club in context["clubs"]
        ]
        context["clubs_json"] = json.dumps(clubs_list)
        return context

src/sejm_app/views/committee_detail_view.py
from sejm_app.models import Committee


from django.views.generic import DetailView


class CommitteeDetailView(DetailView):
    model = Committee
    template_name = "committee_detail.html"  # replace with your template
    context_object_name = "committee"

src/sejm_app/views/committee_list_view.py
from django.views.generic import ListView
from sejm_app.forms import CommitteeSearchForm
from sejm_app.models import Committee


class CommitteeListView(ListView):
    model = Committee
    template_name = "committee_list.html"
    context_object_name = "committees"

    def get_queryset(self):
        queryset = super().get_queryset()
        form = CommitteeSearchForm(self.request.GET)

        if form.is_valid():
            if form.cleaned_data["type"]:
                queryset = queryset.filter(type=form.cleaned_data["type"])
            if form.cleaned_data["appointmentDate_from"]:
                queryset = queryset.filter(
                    appointmentDate__gte=form.cleaned_data["appointmentDate_from"]
                )
            if form.cleaned_data["appointmentDate_to"]:
                queryset = queryset.filter(
                    appointmentDate__lte=form.cleaned_data["appointmentDate_to"]
                )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommitteeSearchForm(self.request.GET)
        return context

src/sejm_app/views/envoy_detail_view.py
from django.views.generic import DetailView
from sejm_app.models import Envoy, Voting, VotingOption, ClubVote, CommitteeMember
from loguru import logger
import json
from django.db import models

# import defaultdict
from collections import defaultdict


class EnvoyDetailView(DetailView):
    model = Envoy
    template_name = "envoy_detail.html"  # replace with your template
    context_object_name = "envoy"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context["interpellations"] = self.object.interpellations.all()
        context["latest_votings"] = self.get_latest_votings(5)
        context["discipline_ratio"] = self.get_discipline_ratio()
        context["member_of"] = CommitteeMember.objects.filter(envoy=self.object)
        # max_activity = 100
        # for envoy in Envoy.objects.all():
        #     if envoy.total_activity > max_activity:
        #         max_activity = envoy.total_activity
        # print(max_activity)
        context["activity"] = int(self.object.total_activity / 1.97)

        return context

    def get_latest_votings(self, n):
        votes = self.object.votes.all()
        votings = (
            Voting.objects.filter(votes__in=votes).distinct().order_by("-date")[:n]
        )
        for voting in votings:
            text_vote = voting.votes.filter(MP=self.object).last().vote_label
            voting.envoy_vote = text_vote
        return votings

    def get_discipline_ratio(self):
        votes = self.object.votes.all()
        votings = Voting.objects.filter(votes__in=votes).distinct().order_by("-date")
        club = self.object.club
        voting_dict = defaultdict(int)
        for voting in votings:
            try:
                club_vote = voting.club_votes.get(club=club)
            except (ClubVote.MultipleObjectsReturned, ClubVote.DoesNotExist):
                logger.warning(f"Club vote for {voting.club_votes.filter(club=club)}")

                continue
            most_popular = (
                VotingOption.NO if club_vote.no > club_vote.yes else VotingOption.YES
            )
            envoy_vote = self.object.votes.get(voting=voting).vote
            if envoy_vote in [
                VotingOption.ABSENT,
                VotingOption.VOTE_VALID,
                VotingOption.ABSTAIN,
            ]:
                voting_dict["brak głosu"] += 1
            elif most_popular == envoy_vote:
                voting_dict["zgodnie"] += 1
            else:
                voting_dict["nie zgodnie"] += 1
                logger.warning(f"envoy vote: {envoy_vote}, club vote: {club_vote}")

        return json.dumps(voting_dict)

src/sejm_app/views/envoy_list_view.py
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView
from sejm_app.models import Envoy, Club
from django.db.models import Count
from django.db.models import Count, F


class EnvoyListView(ListView):
    model = Envoy
    template_name = "envoy_list.html"  # replace with your template
    context_object_name = "envoys"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clubs"] = Club.objects.all()
        context["selected_clubs"] = self.request.GET.getlist("club")
        context["districts"] = Envoy.objects.values("districtName")
        context["selected_districts"] = self.request.GET.getlist("district")
        return context

    def get_queryset(self):
        search_query = self.request.GET.get("searchEnvoys")
        clubs = self.request.GET.getlist("club")
        districts = self.request.GET.getlist("district")
        most_active = self.request.GET.get("most_active")
        queryset = super().get_queryset()
        if search_query:
            query_parts = search_query.strip().split()
            qf = Q()
            for part in query_parts:
                qf &= Q(firstName__icontains=part) | Q(lastName__icontains=part)
            queryset = queryset.filter(qf)
        if clubs:
            queryset = queryset.filter(club__id__in=clubs)
        if districts and "all" not in districts:
            queryset = queryset.filter(districtName__in=districts)
        queryset = queryset.order_by("firstName", "lastName")
        if most_active:
            queryset = sorted(queryset, key=lambda x: x.total_activity, reverse=True)[
                :10
            ]

        return queryset

src/sejm_app/templates/_envoy_snippet.html
{% for envoy in envoys %}
    <div class="col-12 col-md-6 col-lg-6 col-xl-4">
        <a href='{% url "envoy_detail" envoy.id %}'
           style="text-decoration: none;
                  color: inherit"
           class="card clickable-card flex-row mb-4 shadow {% if envoy.numberOfVotes > 100000 %}border-top border-primary{% endif %}">
            <img src='{{ envoy.photo.url }}'
                 loading="lazy"
                 class="card-img-left"
                 alt="{{ envoy.firstName }} {{ envoy.lastName }}">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h5 class="card-title fs-6">{{ envoy.firstName }} {{ envoy.lastName|truncatechars:15 }}</h5>
                </div>
                <span class="badge bg-white rounded p-1 ">
                    <img src="{{ envoy.club.photo.url }}"
                         loading="lazy"
                         alt="Club Photo"
                         style="width: 40px;
                                height: 40px">
                </span>
                {% comment %} {% if envoy.total_activity > 100 %}
                        <p class="col-5 m-1 my-2 badge  text-danger badge border border-dagner pb-0">aktywny/a</p>
                {% endif %} {% endcomment %}
                {% comment %} głosy: {{ envoy.number_of_votes }} {% endcomment %}
            </div>
        </a>
    </div>
{% empty %}
    <div class="col">
        <p>Nie znaleziono żadnego posła.</p>
    </div>
{% endfor %}

src/sejm_app/templates/club_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="container container-fluid">
        <h1 class="text-center">{{ club.name }}</h1>
        <img src="{{ club.photo.url }}"
             class="img-fluid rounded mx-auto d-block"
             alt="{{ club.name }}">
        <p>
            <strong>Phone:</strong> {{ club.phone }}
        </p>
        <p>
            <strong>Fax:</strong> {{ club.fax }}
        </p>
        <p>
            <p>
                <strong>Email:</strong> {{ club.email }}
            </p>
        </p>
        <p>
            <strong>posłowie:</strong> {{ club.members_count }}
        </p>
    </div>
{% endblock %}

src/sejm_app/templates/club_list.html
{% extends 'base.html' %}
{% load math_filters %}
{% load static %}
{% block extra_head %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'js/clubs_chart.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock extra_head %}
{% block content %}
    <div class="container fluid mt-4">
        <h1 class="display-5">Kluby parlamentarne</h1>
        <hr class="my-4">
        <div class="row">
            <div class="row">
                <div class="col-lg-7 col-12">
                    <ul class="list-group mb-3">
                        {% for club in clubs %}
                            <a href="{% url 'club_detail' club.id %}"
                               class="list-group-item d-flex align-items-center rounded border m-1 border clickable-card"
                               style="background: linear-gradient(90deg, rgba(120,120,120,0.2) {{ club.membersCount|divide }}%, transparent {{ club.membersCount|divide }}%)">
                                <span class="bg-white rounded p-1 m-2 me-4">
                                    <img src="{{ club.photo.url }}"
                                         class=""
                                         alt="{{ club.id }}"
                                         style="height: 40px;
                                                width: 40px">
                                </span>
                                <div>
                                    <h5 class="mb-0">{{ club.id }}</h5>
                                    <p class="mb-0">{{ club.membersCount }} posłów</p>
                                </div>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-5 col-12">
                    <canvas id="envoysChart" data-clubs="{{ clubs_json }}"></canvas>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/sejm_app/templates/committee_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="container fluid mt-4">
        <h1 class="display-5">Komisja {{ committee.get_type_display }}: {{ committee.code }}</h1>
        <p class="lead">{{ committee.name }}</p>
        <hr class="my-4">
        <div class="p-1 mb-4">
            <span class="badge badge-primary p-2 me-1">Powołano: {{ committee.appointmentDate }}</span>
            <span class="badge badge-info p-2 ">Telefon: {{ committee.first_phone }}</span>
        </div>
        <h2>Zakres działania</h2>
        <p>{{ committee.scope }}</p>
        <hr class="my-4">
        <h2>Członkowie Komisji ({{ committee.members.all|length }})</h2>
        <div class="row">
            {% for member in committee.members.all %}
                <div class="col-12 col-md-6 col-lg-6 col-xl-4">
                    <a href='{% url "envoy_detail" member.envoy.id %}'
                       style="text-decoration: none;
                              color: inherit"
                       class="card clickable-card flex-row mb-4 shadow">
                        <img src='{{ member.envoy.photo.url }}'
                             loading="lazy"
                             class="card-img-left">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h5 class="card-title fs-6">{{ member.envoy.full_name }}</h5>
                            </div>
                            <span class="badge bg-white rounded p-1 ">
                                <img src="{{ member.envoy.club.photo.url }}"
                                     loading="lazy"
                                     alt="Club Photo"
                                     style="width: 40px;
                                            height: 40px">
                            </span>
                            {% if member.function %}<p class="m-1 my-2 badge badge-primary">{{ member.function }}</p>{% endif %}
                        </div>
                    </a>
                </div>
            {% empty %}
                <div class="alert alert-warning" role="alert">Brak członków w komisji.</div>
            {% endfor %}
        </div>
        <hr class="my-4">
        <h2>Ostatnie Posiedzenia</h2>
        <div class="list-group">
            {% for sitting in committee.sittings.all|slice:":5" %}
                <div class="list-group-item">
                    <h5 class="mb-1">Posiedzenie nr {{ sitting.num }} - Data: {{ sitting.date }}</h5>
                    <p class="mb-1">Agenda</p>
                    <p class="mb-1">{{ sitting.agenda|truncatewords:50 }}</p>
                    {% if sitting.video_id %}
                        <div>
                            <a href="{{ sitting.video_url }}"
                               class="btn btn-primary mt-2"
                               target="_blank">Zobacz wideo</a>
                        </div>
                    {% endif %}
                </div>
            {% empty %}
                <div class="alert alert-warning" role="alert">Brak dostępnych posiedzeń.</div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/sejm_app/templates/committee_list.html
{% extends "base.html" %}
{% block extra_head %}
    <link rel="stylesheet"
          type="text/css"
          href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
    <script type="text/javascript"
            charset="utf8"
            src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript"
            charset="utf8"
            src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
    <script>
$(document).ready( function () {
    $('#committeeTable').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Polish.json"
        }
    });
});
    </script>
    {{ form.media.js }}
    {{ form.media.css }}
{% endblock extra_head %}
{% block content %}
    <div class="modal fade"
         id="helpCommittee"
         tabindex="-1"
         aria-labelledby="envoyModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="envoyModalLabel">Co to jest komisja sejmowa?</h5>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <blockquote class="text-muted fst-italic">
                        Komisje sejmowe to organy pomocnicze Sejmu, powoływane w celu szczegółowego rozpatrywania spraw należących do zakresu działania Sejmu. Podzielone są na stałe i nadzwyczajne, zajmują się przygotowaniem projektów ustaw i sprawozdań z ich realizacji.
                    </blockquote>
                    Zadania i funkcje
                    <hr />
                    <ul>
                        <li>
                            <strong>Przygotowanie ustaw:</strong> Komisje analizują i opiniują projekty ustaw przed ich pierwszym czytaniem w Sejmie.
                        </li>
                        <li>
                            <strong>Kontrola rządu:</strong> Prowadzą działania kontrolne wobec działań rządu i administracji państwowej.
                        </li>
                        <li>
                            <strong>Praca nad specjalistycznymi zagadnieniami:</strong> Każda komisja specjalizuje się w określonej dziedzinie (np. gospodarka, zdrowie), co pozwala na głębszą analizę projektów ustaw.
                        </li>
                        <li>
                            <strong>Organizacja wysłuchań publicznych:</strong> Mogą organizować wysłuchania publiczne w celu zgromadzenia opinii na temat projektów ustaw.
                        </li>
                    </ul>
                    <a href="https://pl.wikipedia.org/wiki/Komisja_sejmowa" target="_blank">Więcej na temat komisji sejmowych na Wikipedii</a>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container container-fluid mt-4">
        <div class=" display-5  d-flex justify-content-between">
            Komisje sejmowe
            <span>
                <i class="fa-solid fa-circle-info mx-1 fs-3 text-primary"
                   data-bs-toggle="modal"
                   data-bs-target="#helpCommittee"></i>
            </span>
        </div>
        <hr class="my-4">
        <div class="row">
            <div class="col-md-3  p-2 pt-0">
                {% load crispy_forms_tags %}
                <form method="get" class="rounded border p-3 " novalidate>
                    <h4 class="text-danger ">Filtruj</h4>
                    <hr class="my-4 text-danger">
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary m-2">Filtruj</button>
                    <button type="reset" class="btn btn-secondary m-2">Resetuj filtry</button>
                </form>
            </div>
            <div class="col-9">
                <table id="committeeTable" class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>Kod</th>
                            <th>Nazwa</th>
                            <th>Typ</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for committee in committees %}
                            <tr>
                                <td>{{ committee.code }}</td>
                                <td>
                                    <a href="{% url 'committee_detail' committee.code %}">{{ committee.name }}</a>
                                </td>
                                <td>{{ committee.get_type_display }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="6" class="text-center">Nie znaleziono komisji</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/sejm_app/templates/voting_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="container fluid mt-4">
        <div class="alert alert-warning" role="alert">Widok w przygotowaniu...</div>
        <h1 class="display-5 ">Głosowanie z dnia: {{ voting.date }}</h1>
        <hr class="my-4">
    </div>
{% endblock %}